name: Android Emulator with Public GUI via Ngrok

on:
  workflow_dispatch:

jobs:
  android-emulator:
    runs-on: self-hosted  # IMPORTANT: must be a self-hosted runner or cloud VM

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Start Android Emulator with GUI
        run: |
          docker run --name android-emulator -d \
            --privileged \
            -e DEVICE="Samsung Galaxy S6" \
            -e AUTO_RECORD=false \
            -p 6080:6080 \
            budtmo/docker-android:emulator_13.0

      - name: Install ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok -y

      - name: Authenticate ngrok
        run: ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}

      - name: Start ngrok tunnel for Android GUI (port 6080)
        run: |
          nohup ngrok http 6080 > ngrok.log 2>&1 &
          sleep 6
          echo "Fetching ngrok public URL..."
          curl http://127.0.0.1:4040/api/tunnels > tunnels.json
          cat tunnels.json
          echo "🔗 Public Android GUI URL:"
          jq -r '.tunnels[0].public_url' tunnels.json
