name: Android Emulator with GUI via Ngrok

on:
  workflow_dispatch:

jobs:
  run-emulator:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Start Android Emulator with GUI
        run: |
          docker run --privileged -d -p 6080:6080 \
            -e DEVICE="Samsung Galaxy S6" \
            budtmo/docker-android-x86-13.0

      - name: Install ngrok
        run: |
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          sudo mv ngrok /usr/local/bin

      - name: Auth ngrok
        run: ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}

      - name: Start tunnel
        run: |
          nohup ngrok http 6080 > /dev/null 2>&1 &
          sleep 8
          curl http://localhost:4040/api/tunnels > tunnels.json
          cat tunnels.json
          echo "🔗 Public Android GUI:"
          jq -r '.tunnels[0].public_url' tunnels.json
