image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start Android Emulator
    command: |
      docker run --privileged -d \
        -p 6080:6080 \
        -e DEVICE="Samsung Galaxy S10" \
        -e WEB_VNC=true \
        budtmo/docker-android:emulator_11.0

ports:
  - port: 6080
    onOpen: open-preview
    visibility: public
