name: Android Emulator with GUI Recording

on:
  workflow_dispatch:

jobs:
  android-emulator:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Start Android Emulator in Docker (GUI Enabled)
        run: |
          docker run --name android-emulator -d \
            --privileged \
            -e DEVICE="Samsung Galaxy S6" \
            -e AUTO_RECORD=false \
            -e EMULATOR_ARGS="-no-audio" \
            -p 6080:6080 -p 5554:5554 -p 5555:5555 \
            budtmo/docker-android:emulator_13.0

      - name: Wait for Emulator to Boot
        run: |
          echo "⏳ Waiting 60 seconds for emulator to start..."
          sleep 60
          docker exec android-emulator adb wait-for-device

          echo "🔍 Checking boot status..."
          boot_completed=""
          until [[ "$boot_completed" == "1" ]]; do
            sleep 5
            boot_completed=$(docker exec android-emulator adb shell getprop sys.boot_completed | tr -d '\r')
            echo "Boot status: $boot_completed"
          done
          echo "✅ Emulator is ready!"

      - name: Record Emulator Screen
        run: |
          docker exec android-emulator adb shell screenrecord /sdcard/boot.mp4 &
          sleep 20
          docker exec android-emulator adb pull /sdcard/boot.mp4 /tmp/boot.mp4

      - name: Upload Emulator Video
        uses: actions/upload-artifact@v4
        with:
          name: boot-video
          path: /tmp/boot.mp4

      - name: Cleanup
        if: always()
        run: |
          docker stop android-emulator
          docker rm android-emulator
