name: Show My Secret

on:
  workflow_dispatch:  # Allows manual trigger from the Actions tab

jobs:
  show-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Show My Secret (safe demo)
        run: |
          echo "My secret is: ${{ secrets.MY_SECRET }}"
