name: Android Emulator with GUI via Ngrok

on:
  workflow_dispatch:

jobs:
  run-emulator:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Docker (for Ubuntu 24.04+)
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          sudo usermod -aG docker $USER || true

      - name: Start Android Emulator (Android 13 + GUI)
        run: |
          sudo docker run --privileged -d -p 6080:6080 \
            -e DEVICE="Samsung Galaxy S6" \
            --name android-emulator \
            budtmo/docker-android:emulator_13.0

      - name: Install Ngrok
        run: |
          wget -q https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          sudo mv ngrok /usr/local/bin

      - name: Authenticate Ngrok
        run: ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}

      - name: Start Ngrok Tunnel for Android GUI (6080)
        run: |
          nohup ngrok http 6080 > /dev/null 2>&1 &
          sleep 10
          curl -s http://127.0.0.1:4040/api/tunnels > tunnels.json
          echo "🔗 Android Public GUI Link:"
          cat tunnels.json | jq -r '.tunnels[0].public_url'
